package mapreduce

import (
	"bufio"
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"log"
	"os"
	"sort"
)

type KInt struct {
	Key string
	Value int
}

func Min(i, j int) int {
	if i < j {
		return i
	} else {
		return j
	}
}

type KInts []KInt

func (kvs KInts) Len() int      { return len(kvs) }
func (kvs KInts) Swap(i, j int) { kvs[i], kvs[j] = kvs[j], kvs[i] }
func (kvs KInts) Less(i, j int) bool {
	k1, k2 := kvs[i].Key, kvs[j].Key
	for i, bound := 0, Min(len(k1), len(k2)); i < bound; i++ {
		if k1[i] < k2[i] {
			return true
		} else if k1[i] > k2[i] {
			return false
		}
	}
	return len(k1) < len(k2)
}

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	dat, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal("Map[Read]: ", err)
		panic(err)
	}

	pars := make([][]KInt, nReduce)
	kvs := mapF(inFile, string(dat))

	// partition
	for i, kv := range kvs {
		parIdx := ihash(kv.Key) % nReduce
		pars[parIdx] = append(pars[parIdx], KInt{kv.Key, i})
	}

	// sort
	for i, keys := range pars {
		if keys == nil {
			continue
		}

		f, err := os.Create(reduceName(jobName, mapTask, i))
		if err != nil {
			log.Fatal("Map[Write]: ", err)
			panic(err)
		}

		w := bufio.NewWriter(f)
		enc := json.NewEncoder(w)

		sort.Sort(KInts(keys))

		for _, key := range keys {
			enc.Encode(&kvs[key.Value])
		}
		w.Flush()
		f.Close()
	}
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
